static char *air[] = {
    "Clear",
    "Clear",
    "Clear",
    "Clear",
    "Clear",
    "Clear",
    "Clear",
    "Clear",
    "Clear",
    "Clear",
    "Clear",
    "Clear",
    "Clear",
    "Clear",
    "Clear",
    "Clear",
    "Clear",
    "Clear",
    "Clear",
    "Clear",
    "Clear",
    "Clear",
    "Clear",
    "Clear",
    "Clear",
    "Clear",
    "Clear",
    "Clear",
    "Clear",
    "Clear",
    "Clear",
    "Clear",
    "Clear",
    "Clear",
    "Clear",
    "Clear",
    "Clear",
    "Clear",
    "Clear",
    "Clear",
    "Clear",
    "Clear",
    "Clear",
    "Clear",
    "Clear",
    "Clear",
    "Clear",
    "Clear",
    "Clear",
    "Clear",
    "Clear",
    "Clear",
    "Clear",
    "Clear",
    "Clear",
    "Clear",
    "Clear",
    "Clear",
    "Clear",
    "Clear",
    "Clear",
    "Clear",
    "Clear",
    "Clear",
    "Clear",
    "Clear",
    "Clear",
    "Clear",
    "Clear",
    "Clear",
    "Foggy",
    "Foggy",
    "Foggy",
    "Foggy",
    "Foggy",
    "Foggy",
    "Foggy",
    "Foggy",
    "Foggy",
    "Foggy",
    "Foggy near Floor",
    "Foggy near Floor",
    "Foggy near Floor",
    "Foggy near Floor",
    "Foggy near Floor",
    "Foggy near Floor",
    "Foggy near Floor",
    "Foggy near Floor",
    "Hazy, Dust",
    "Hazy, Dust",
    "Hazy, Smoke",
    "Hazy, Smoke",
    "Hazy, Smoke",
    "Hazy, Smoke",
    "Hazy, Smoke",
    "Hazy, Smoke",
    "Hazy, Smoke",
    "Hazy, Smoke",
    "Misted",
    "Misted",
    "End of List",
    "End of List"
};
char *air_currents[] = {
    "Slight Breeze",
    "Slight Breeze",
    "Slight Breeze",
    "Slight Breeze",
    "Slight Breeze",
    "Slight Damp Breeze",
    "Slight Damp Breeze",
    "Slight Damp Breeze",
    "Slight Damp Breeze",
    "Slight Damp Breeze",
    "Gusting Breeze",
    "Gusting Breeze",
    "Cold Air Current",
    "Cold Air Current",
    "Cold Air Current",
    "Cold Air Current",
    "Cold Air Current",
    "Cold Air Current",
    "Slight Downdraft",
    "Slight Downdraft",
    "Strong Downdraft",
    "Strong Downdraft",
    "Still Air",
    "Still Air",
    "Still Air",
    "Still Air",
    "Still Air",
    "Still Air",
    "Still Air",
    "Still Air",
    "Still Air",
    "Still Air",
    "Still Air",
    "Still Air",
    "Still Air",
    "Still Air",
    "Still Air",
    "Still Air",
    "Still Air",
    "Still Air",
    "Still Air",
    "Still Air",
    "Still Air",
    "Still Air",
    "Still Air",
    "Still Air",
    "Still Air",
    "Still Air",
    "Still Air",
    "Still Air",
    "Still Air",
    "Still Air",
    "Still Air",
    "Still Air",
    "Still Air",
    "Still Air",
    "Still Air",
    "Still Air",
    "Still Air",
    "Still Air",
    "Still Air",
    "Still Air",
    "Still Air",
    "Still Air",
    "Still Air",
    "Still Air",
    "Still Air",
    "Still Air",
    "Still Air",
    "Still Air, Very Chill",
    "Still Air, Very Chill",
    "Still Air, Very Chill",
    "Still Air, Very Chill",
    "Still Air, Very Chill",
    "Still Air, Very Chill",
    "Still Air, Hot",
    "Still Air, Hot",
    "Still Air, Hot",
    "Still Air, Hot",
    "Still Air, Hot",
    "Still Air, Hot",
    "Still Air, Hot",
    "Still Air, Hot",
    "Still Air, Hot",
    "Still Air, Hot",
    "Slight Updraft",
    "Slight Updraft",
    "Strong Updraft",
    "Strong Updraft",
    "Strong Wind",
    "Strong Wind",
    "Strong Wind",
    "Strong Wind",
    "Strong Gusting Wind",
    "Strong Gusting Wind",
    "Strong Moaning Wind",
    "Strong Moaning Wind",
    "Strong Moaning Wind",
    "Strong Moaning Wind",
    "Strong Moaning Wind"
};
char *junk[] = {
    "Broken Arrow",
    "Ashes",
    "Ashes",
    "Ashes",
    "Bones",
    "Bones",
    "Broken Bottle",
    "Corroded Chain",
    "Splitered Club",
    "Cobwebs",
    "Cobwebs",
    "Cobwebs",
    "Cobwebs",
    "Cobwebs",
    "Cobwebs",
    "Cobwebs",
    "Cobwebs",
    "Cobwebs",
    "Cobwebs",
    "Copper Piece",
    "Ceiling Cracks",
    "Ceiling Cracks",
    "Floor Cracks",
    "Floor Cracks",
    "Wall Cracks",
    "Wall Cracks",
    "Dagger Hilt",
    "Ceiling Damp",
    "Ceiling Damp",
    "Wall Damp",
    "Wall Damp",
    "Wall Damp",
    "Wall Damp",
    "Water Dripping",
    "Water Dripping",
    "Water Dripping",
    "Water Dripping",
    "Water Dripping",
    "Water Dripping",
    "Water Dripping",
    "Dried Blood",
    "Dung",
    "Dung",
    "Dung",
    "Dust",
    "Dust",
    "Dust",
    "Dust",
    "Dust",
    "Cracked Flask",
    "Food Scraps",
    "Fungi, Common",
    "Bat Guano",
    "Bat Guano",
    "Bat Guano",
    "Hair or fur bits",
    "Cracked Hammer Head",
    "Helm",
    "Iron bar",
    "Blunt Javlin Head",
    "Leather Boot",
    "Leaves and twigs",
    "Leaves and twigs",
    "Leaves and twigs",
    "Mold, Common",
    "Mold, Common",
    "Mold, Common",
    "Mold, Common",
    "Pick Handle",
    "Broken Pole",
    "Pottry Shards",
    "Rags",
    "Rags",
    "Rotten Rope",
    "Rubble",
    "Rubble",
    "Torn Sack",
    "Slimy Ceiling",
    "Slimy Floor",
    "Slimy Wall",
    "Rusted Spike",
    "Sticks",
    "Sticks",
    "Small Stones",
    "Straw",
    "Broken Sword",
    "Fangs",
    "Touch Stub",
    "Scratchings on Wall",
    "Small Water Puddle",
    "Small Water Puddle",
    "Large Water Puddle",
    "Large Water Puddle",
    "Water Trickles",
    "Water Trickles",
    "Wax Drippings",
    "Wax Blob",
    "Rotting Wood Pieces",
    "Rotting Wood Pieces",
    "Rotting Wood Pieces",
    "End of List",
    "End of List"
};
struct monster_str {
    char name[32];
    int hit_dice;
    int max_num;
};

char *odors[] = {
    "Acrid",
    "Acrid",
    "Acrid",
    "Chlorine",
    "Chlorine",
    "Dank, Mouldy",
    "Dank, Mouldy",
    "Dank, Mouldy",
    "Dank, Mouldy",
    "Dank, Mouldy",
    "Dank, Mouldy",
    "Dank, Mouldy",
    "Dank, Mouldy",
    "Dank, Mouldy",
    "Dank, Mouldy",
    "Dank, Mouldy",
    "Dank, Mouldy",
    "Dank, Mouldy",
    "Dank, Mouldy",
    "Dank, Mouldy",
    "Dank, Mouldy",
    "Dank, Mouldy",
    "Dank, Mouldy",
    "Dank, Mouldy",
    "Dank, Mouldy",
    "Dank, Mouldy",
    "Dank, Mouldy",
    "Dank, Mouldy",
    "Dank, Mouldy",
    "Dank, Mouldy",
    "Dank, Mouldy",
    "Dank, Mouldy",
    "Dank, Mouldy",
    "Dank, Mouldy",
    "Dank, Mouldy",
    "Dank, Mouldy",
    "Dank, Mouldy",
    "Dank, Mouldy",
    "Dank, Mouldy",
    "Earthy",
    "Earthy",
    "Earthy",
    "Earthy",
    "Earthy",
    "Earthy",
    "Earthy",
    "Earthy",
    "Earthy",
    "Earthy",
    "Manure",
    "Manure",
    "Manure",
    "Manure",
    "Manure",
    "Manure",
    "Manure",
    "Manure",
    "Metallic",
    "Metallic",
    "Metallic",
    "Metallic",
    "Ozone",
    "Ozone",
    "Ozone",
    "Ozone",
    "Putrid",
    "Putrid",
    "Putrid",
    "Putrid",
    "Putrid",
    "Rotting Vegetation",
    "Rotting Vegetation",
    "Rotting Vegetation",
    "Rotting Vegetation",
    "Rotting Vegetation",
    "Salty, Wet",
    "Salty, Wet",
    "Smokey",
    "Smokey",
    "Smokey",
    "Smokey",
    "Smokey",
    "Stale, Fetid",
    "Stale, Fetid",
    "Stale, Fetid",
    "Stale, Fetid",
    "Stale, Fetid",
    "Stale, Fetid",
    "Stale, Fetid",
    "Sulphurous",
    "Sulphurous",
    "Sulphurous",
    "Sulphurous",
    "Sulphurous",
    "Sulphurous",
    "Urine",
    "Urine",
    "Urine",
    "Urine",
    "Urine",
    "End of list",
};
char *sounds[] = {
    "Bang or Slam",
    "Bang or Slam",
    "Bang or Slam",
    "Bang or Slam",
    "Bang or Slam",
    "Bellow",
    "Bong",
    "Buzzing",
    "Chanting",
    "Chanting",
    "Chiming",
    "Chirping",
    "Clanking",
    "Clashing",
    "Clicking",
    "Coughing",
    "Creaking",
    "Creaking",
    "Druming",
    "Footsteps ahead",
    "Footsteps ahead",
    "Footsteps ahead",
    "Footsteps ahead",
    "Footsteps approaching",
    "Footsteps approaching",
    "Footsteps approaching",
    "Footsteps behind",
    "Footsteps behind",
    "Footsteps behind",
    "Footsteps receding",
    "Footsteps receding",
    "Footsteps to the side",
    "Footsteps to the side",
    "Faint Giggling",
    "Faint Giggling",
    "Gong",
    "Grating",
    "Grating",
    "Grating",
    "Growning",
    "Growning",
    "Grunting",
    "Hissing",
    "Hissing",
    "Hooting",
    "Horn or trumpet",
    "Howling",
    "Humming",
    "Jingling",
    "Knocking",
    "Knocking",
    "Knocking",
    "Knocking",
    "Laughter",
    "Laughter",
    "Moaning",
    "Moaning",
    "Murmuring",
    "Murmuring",
    "Murmuring",
    "Music",
    "Rattling",
    "Ringing",
    "Roaring",
    "Rustling",
    "Rustling",
    "Rustling",
    "Rustling",
    "Scratching",
    "Scratching",
    "Scratching",
    "Scratching",
    "Screaming",
    "Screaming",
    "Scuttling",
    "Scuttling",
    "Scuttling",
    "Shuffling",
    "Slithering",
    "Slithering",
    "Snapping",
    "Sneezing",
    "Sobbing",
    "Splashing",
    "Splitering",
    "Squeaking",
    "Squeaking",
    "Squealing",
    "Tapping",
    "Tapping",
    "Thud",
    "Thud",
    "Thumping",
    "Thumping",
    "Tinkling",
    "Twanging",
    "Whining",
    "Whispering",
    "Whistling",
    "Whistling",
    "End of List",
    "End of List",
    "End of List"
};
char *traps[] = {
    "Arrow Trap",
    "Arrow Trap",
    "Arrow Trap",
    "Arrow Trap",
    "Arrow Trap",
    "Arrow Trap, Poisoned",
    "Ball Trap",
    "Caltropes",
    "Caltropes",
    "Caltropes, Poisoned",
    "Ceiling block falls",
    "Ceiling collapses",
    "Ceiling lowers",
    "Chute",
    "Chute",
    "Chute",
    "Falling Door",
    "Falling Door",
    "One Way Door",
    "One Way Door",
    "One Way Door",
    "One Way Door",
    "One Way Door",
    "Resisting Door",
    "Resisting Door",
    "Resisting Door",
    "Resisting Door",
    "Resisting Door",
    "Resisting Door",
    "Resisting Door",
    "Class or Race Specific Door",
    "Spring Door",
    "Floor collapes",
    "Floor Illusionary",
    "Blinding Gas",
    "Blinding Gas",
    "Corroding Gas",
    "Corroding Gas",
    "Fear Gas",
    "Fear Gas",
    "Nausea Gas",
    "Nausea Gas",
    "Smoke Screen",
    "Smoke Screen",
    "Smoke Screen",
    "Smoke Screen",
    "Poison Gas",
    "Poison Gas",
    "Sleep Gas",
    "Sleep Gas",
    "Slowing Gas",
    "Slowing Gas",
    "Weakness Gas",
    "Weakness Gas",
    "Jaw Trap",
    "Jaw Trap",
    "Lightning Bolt",
    "Pendulum Ball or Blade",
    "Pendulum Ball or Blade",
    "Pit",
    "Pit",
    "Pit",
    "Pit",
    "Locking Pit",
    "Locking Pit",
    "Locking Pit, Flooding",
    "Locking Pit, Flooding",
    "Pits with Spikes",
    "Pits with Spikes",
    "Pits with Spikes",
    "Pits with Poisoned Spikes",
    "Pits with Poisoned Spikes",
    "Passage Blocked by falling bars",
    "Passage Blocked by falling bars",
    "Passage Blocked by falling bars",
    "Passage Blocked by falling bars",
    "Passage Blocked by falling bars",
    "Passage Blocked by stone blocks",
    "Passage Blocked by stone blocks",
    "Elevator Room",
    "Flooding Room",
    "Sliding Room",
    "Scything blades",
    "Scything blades",
    "Spear Trap",
    "Spear Trap",
    "Spear Trap",
    "Spear Trap, Poisoned",
    "Collapsing Stairs",
    "Teleporter",
    "Teleporter",
    "Acid Vent",
    "Fire Vent",
    "Fire Vent",
    "Gas Vent",
    "Gas Vent",
    "Gas Vent",
    "Gas Vent",
    "Gas Vent",
    "Gas Vent",
    "End of List",
    "End of List",
    "End of List"
};
