

DIRS=accrete GenSec4 planetgen stargen worldgen ExtSys SysGen4

all:
	cd accrete; make
	cd GenSec4; make
	cd planetgen; make
	cd stargen; make
	cd worldgen; make
	cd ExtSys; make
	cd SysGen4; make

clean:
	cd accrete; make clean
	cd GenSec4; make clean
	cd planetgen; make clean
	cd stargen; make clean
	cd worldgen; make clean
	cd ExtSys; make clean
	cd SysGen4; make clean
