const char   *soccust[168] = {
    "Same clothes for all sexes",
    "Unusual clothes for %s",
    "Unusual headgear for %s",
    "Shaved heads for %s",
    "Hair never cut for %s",
    "Unusual hair colour for %s",
    "Unusual hairdos for %s",
    "Unusual eyebrows for %s",
    "Unusuaal facial alterations for %s",
    "Unusual body alterations for %s",
    "Unusual fingernails for %s",
    "Unusual toenails for %s",
    "Unusual cosmetics for %s",
    "Unusual jewelery for %s",
    "Unusual accessories for %s",
    "Unusual handgear for %s",
    "Tatooing on face of %s",
    "Tatooing on body of %s",
    "Hidden tatooing of %s",
    "Unusual foods for %s",
    "Unusual beverages for %s",
    "Unusual food preparation for %s",
    "%s segregated during meals",
    "%s are vegetarians",
    "%s are carnivorous",
    "%s are omnivorous",
    "Certain coloured food is taboo for %s",
    "Certain shaped food is taboo for %s",
    "Certain food sources are taboo for %s",
    "%s eat in special location",
    "%s eat only in private",
    "%s eat in special orientation",
    "%s eat with unusual utensils",
    "%s eat only at home",
    "%s eat at unusual times",
    "%s eat at only certain times",
    "%s eat only in certain ways",
    "Rituals before eating for %s",
    "Rituals after eating for %s",
    "One sex eats other's leftovers",
    "One age eats other's leftovers",
    "%s eats %s leftovers",
    "One class eats other's leftovers",
    "One race eats others leftovers",
    "%s are cannibalistic",
    "%s live privately",
    "%s live apart in groups",
    "%s live in special locations",
    "%s live at place of work",
    "%s live under special conditions",
    "%s are confined to quarters",
    "%s live under special care",
    "%s have extravagant quarters",
    "%s have minimal quarters",
    "%s have unusual quarters",
    "%s quarters are taboo for %s",
    "%s must visit %s quarters",
    "%s live with extended families",
    "%s live with groom's family",
    "%s live with bride's family",
    "%s live with children's family",
    "%s live with relatives",
    "%s live in communal housing",
    "%s live only in certain terrain",
    "%s must move around",
    "Child named by %s",
    "Child named for living relative",
    "Child named for dead relative",
    "Child named for hero",
    "Child named for %s",
    "Child named for object",
    "Child renamed at adulthood",
    "Child renamed when married",
    "Marriage arranged by %s",
    "Marriage performed by %s",
    "Marriage arranged by parents",
    "Marriage performed by parents",
    "Marriage only within %s",
    "Remarriage prohibited for %s",
    "Remarriage required for %s",
    "Groom's family pays dowery for %s",
    "Bride's family pays dowery for %s",
    "Dowery paud by outsider for %s",
    "Very short marriages the rule for %s",
    "Very long marriages the ruse for %s",
    "Non-marriage the rule for %s",
    "Very short marriages prohibited for %s",
    "Very long marriages prohibited for %s",
    "Non-marriage prohibited for %s",
    "Divorce and remarriage required for %s",
    "%s's widow must marry husband's relative",
    "%s's widow/widower must commit suicide",
    "%s's widower must marry wife's relative",
    "Onerous prerequisite to marriage for %s",
    "Marriage only at certain times for %s",
    "Marriage must be blessed by %s",
    "Polyandry practiced amongst %s",
    "Polygyny practiced amongst %s",
    "Communal polygamy practices amongst %s",
    "Unusual sleeping loaction for %s",
    "Unusual sleeping time for %s",
    "Unusual sleep duration for %s",
    "Unusual sleep orientation for %s",
    "Special language for %s",
    "Sacred symbols for %s",
    "Unusual duties for %s",
    "Anonimity required for %s",
    "Drinking/drugs prohibited for %s",
    "Drinking/drugs required for %s",
    "Bodily abuse prohibited for %s",
    "Bodily abuse required for %s",
    "Special privileges for %s",
    "Special priviliges prohibited for %s",
    "Unusual greetings for %s",
    "Unusual mannerisms for %s",
    "Unusual leavetakings for %s",
    "Unusual secret societies amongst %s",
    "Closed meetings taboo for %s",
    "Psionics allowed for %s",
    "Psionics mean instant death for %s",
    "Cloning allowed for %s",
    "Cloning required for %s",
    "Cloning prohibited for %s",
    "Robots allowed for %s",
    "Robots required for %s",
    "Robots prohibited for %s",
    "High-tech allowed for %s",
    "High-tech prohibited for %s",
    "Offworld contact allowed for %s",
    "Offworld contact required for %s",
    "Offworld contact prohibited for %s",
    "Unusal gift-giving customs by %s",
    "Free food/clothing required for %s",
    "Free food/clothing prohibited for %s",
    "Free education required for %s",
    "Free education prohibited for %s",
    "Unusual punishment required for %s",
    "Unusual punishment prohibited for %s",
    "Unusual training required for %s",
    "Unusual training prohibited for %s",
    "Unusual responsibilities for %s",
    "Fixed times for visiting %s",
    "Bargaining/haggling required for %s",
    "Bargaining/haggling prohibited ofr %s",
    "Travelling far away required for %s",
    "Travelling far away prohibited for %s",
    "Unusual holidays for %s",
    "No holidays for %s",
    "Unusual leasure/recreation for %s",
    "Regimented leasure/recreation for %s",
    "Unusual maturity ceremony for %s",
    "Unusual attitudes toward %s",
    "Unusual significance of flora for %s",
    "Unusual significance of fauna for %s",
    "Unusual significance of smell for %s",
    "Unusual significance of sound for %s",
    "Unusual significance of colour for %s",
    "Unusual significance of air for %s",
    "Unusual significance of water for %s",
    "Unusual significance of light for %s",
    "Unusual significance of clothing for %s",
    "Unusual significance of computers for %s",
    "Unusual significance of technology for %s",
    "Unusual significance of robots for %s",
    "Unusual significance of art for %s",
    "Unusual significance of superstition for %s",
    "Daytime siesta required for %s",
    "Daytime siesta prohibited for %s"
};

const char   *pracgroup[19] = {
    "Certain political figures",
    "Certain geographical regions",
    "Certain sex",
    "Enforcement figures",
    "Entertainment figures",
    "Heroic Figures",
    "Athletic Figures",
    "Certain races",
    "Religious figures",
    "Military figures",
    "Certain occupations",
    "Political figures",
    "Medical figures",
    "Certain age groups",
    "Scientific figures",
    "Academic figures",
    "Low social class",
    "High social class",
    "Convicted criminals"
};

const char   *agodv[16] = {
    "Animism",
    "Polytheistic Animism",
    "Polytheism",
    "Rational Polytheism",
    "Dualism",
    "Interactive Monotheism",
    "Influential Monotheism",
    "Crisis Monotheism",
    "Remote Monotheism",
    "Deism",
    "Pantheism",
    "Agnosticism",
    "Rational Atheism",
    "Skeptical Atheism",
    "Atheism",
    "Philosophical Atheism"
};

const char   *asaim[16] = {
    "Worshipers are a chosen elite who deserve to dominate.",
    "Worshipers will be rewarded in this life.",
    "Worshipers will be saved from some imminent disaster.",
    "Reincarnation with a karma doctrine.",
    "Statistical reincarnation causes a return in a merit awarded form.",
    "Worshippers will be received into paradise when they die.",
    "Worshippers will avoid being condemned to a place of eternal punishment.",
    "Ethical and moral standards are their own reward.",
    "Believers perform charitable acts to build a better society.",
    "Believers seek to promote peace and harmony for all.",
    "Believers seek to expand knowledge through inquiry and speculation.",
    "Believers seek to preserve the wisdom of the past.",
    "Believers seek to improve their own lives by by self-discipline.",
    "Hedonism is the only proper purpose in life.",
    "There is no purpose in life and nothing is to be gained by living."
};

const char   *adreq[16] = {
    "Constant",
    "Several times per hour",
    "Hourly",
    "Several times per day",
    "Daily",
    "Several days per week",
    "Weekly",
    "Semi-weekly",
    "Monthly",
    "Semi-monthly",
    "Quarterly",
    "Bi-annually",
    "Yearly",
    "Several times during life",
    "At least once before death",
    "None"
};

const char   *arog[16] = {
    "Theocracy",
    "Rigid hierarchy with centrailsed authority",
    "Rigid hierarchy with regional authority",
    "Rigid hierarchy with planetary authority",
    "Rigid hierarchy with local authority",
    "Loose hierarchy with centrailsed authority",
    "Loose hierarchy with regional authority",
    "Loose hierarchy with planetary authority",
    "Loose hierarchy with local authority",
    "Loose hierarchy with individual authority",
    "No organisation above regional level",
    "No organisation above planetary level",
    "No organisation above local level",
    "Local organisation without regulations",
    "Loose highly informal organisation",
    "No organisation at all"
};

const char   *litf[16] = {
    "Word of God is pronounced by living oracles",
    "Holy writings accessible by high clergy",
    "Holy writings accessibly by clergy",
    "Services conducted by rote in obscure religious language",
    "Services conducted by rote in common language",
    "Very formal church service",
    "Formal church service and limited teaching",
    "Rituals are combined with moderate teaching",
    "Rituals are combined with open teaching",
    "Communal teaching with limited ritual",
    "Formal study groups of church writings",
    "Formal study groups investigating wider applications of church writings",
    "Informal study groups on limited tobics",
    "Informal liturgy with minor restraints",
    "Open exchange of ideas in conversational setting",
    "Religion not discussed"
};

const char   *amiss[11] = {
    "Zealous conversion of all",
    "Zealous conversion of limited races",
    "Zealous but racist",
    "Active conversion of all",
    "Active conversion of limited races",
    "Active conversion but racist",
    "Ordinary conversion of all",
    "Ordinary conversion of limited races",
    "Ordinary conversion but racist",
    "Occasional",
    "Highly infrequent"
};

const char   *bodsiz[] = {
    "1m", "5m", "10m", "25m", "50m", "100m", "300m",
    "1km", "5km", "10km", "50km", "100km", "500km", "1000km"
};

const char   *patt[] = { "Radical", "Progressive", "Conservative", "Reactionary" };
const char   *pact[] = { "Enterprising", "Advancing", "Indifferent", "Stagnant" };
const char   *aatt[] = { "Expansionistic", "Competitive", "Unaggressive", "Passive"};
const char   *aact[] = { "Militant", "Neutral", "Peaceable", "Conciliatory" };
const char   *eglo[] = { "Monolithic", "Harmonious", "Discordant", "Fragmented" };
const char   *eint[] = { "Xenophilic", "Friendly", "Aloof", "Xenophobic" };
const char   *aatmos[] = {
    "Vaccuum", "Trace", "Very Thin (tainted)", "Very Thin",
    "Thin (tainted)", "Thin", "Standard (tainted)", "Standard",
    "Dense (tainted)", "Dense", "Exotic", "Corrosive",
    "Insidious", "Dense, High", "Elipsoid", "Thin,Low"
};

const char   *agov[] = {
    "No Government Structure",
    "Company/Corporation",
    "Participating Democracy",
    "Self-Perpetuating Oligarchy",
    "Representative Democracy",
    "Feudal Technocracy",
    "Captive Government",
    "Balkanization",
    "Civil Service Bureaucracy",
    "Impersonal Bureaucracy",
    "Charismatic Dictator",
    "Non-Charismatic Dictator",
    "Charismatic Oligarchy",
    "Religious Dictatorship",
    "Religious Autocracy",
    "Totalitarian Oligarchy"
};

